name: 0.0.$(Date:yyMM.d)$(Rev:rrr)

pr: none
trigger:
  - main

pool: OE-OfficePublic

variables:
  - group: Hermes-Windows Secrets
  - group: InfoSec-SecurityResults
  - name: ArtifactServices.Symbol.AccountName
    value: microsoft
  - name: ArtifactServices.Symbol.PAT
    value: $(pat-symbols-publish-microsoft)
  - name: tags
    value: production,externalfacing

jobs:
  - template: jobs.yml